In [19]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import datetime as dt
import warnings
warnings.filterwarnings("ignore")

In [20]:
data = pd.read_csv("WashingtonMay.csv")

## YearMonth

In [21]:
dataSubYearMonth = data.copy()

In [22]:
dataSubYearMonth['crashPctChange'] = dataSubYearMonth.Crash_ID.pct_change()
dataSubYearMonth['deathCntPctChange'] = dataSubYearMonth.Death_Cnt.pct_change()
dataSubYearMonth['fatalPctChange'] = dataSubYearMonth.Crash_Fatal_Fl.pct_change()
dataSubYearMonth['State']='Washington'
dataSubYearMonth['Country']='United States'

In [23]:
dataSubYearMonth['deathRate']=dataSubYearMonth['Death_Cnt']/dataSubYearMonth['Crash_ID']
dataSubYearMonth['fatRate']=dataSubYearMonth['Crash_Fatal_Fl']/dataSubYearMonth['Crash_ID']

In [24]:
dataSubYearMonth['deathRatePctChange'] = dataSubYearMonth.deathRate.pct_change()
dataSubYearMonth['fatRatePctChange'] = dataSubYearMonth.fatRate.pct_change()

In [25]:
with open("WA_dataSubYearMonth.csv",'w', newline='') as outputfile:
    dataSubYearMonth.to_csv(outputfile, header=True, index = False)

In [26]:
datacheck = pd.read_csv('WA_dataSubYearMonth.csv')

In [27]:
datacheck

    Year  Month  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth  crashPctChange  deathCntPctChange  fatalPctChange       State        Country  deathRate   fatRate  deathRatePctChange  fatRatePctChange
0   2019      1     13260              63        NaN   2019-01             NaN                NaN             NaN  Washington  United States        NaN  0.004751                 NaN               NaN
1   2019      2     12826              37        NaN   2019-02       -0.032730                NaN       -0.412698  Washington  United States        NaN  0.002885                 NaN         -0.392826
2   2019      3     11917              62        NaN   2019-03       -0.070872                NaN        0.675676  Washington  United States        NaN  0.005203                 NaN          0.803492
3   2019      4     11819              41        NaN   2019-04       -0.008224                NaN       -0.338710  Washington  United States        NaN  0.003469                 NaN         -0.333226
4   2019      5     13215              51        NaN   2019-05        0.118115                NaN        0.243902  Washington  United States        NaN  0.003859                 NaN          0.112500
5   2019      6     12969              63        NaN   2019-06       -0.018615                NaN        0.235294  Washington  United States        NaN  0.004858                 NaN          0.258726
6   2019      7     13073              65        NaN   2019-07        0.008019                NaN        0.031746  Washington  United States        NaN  0.004972                 NaN          0.023538
7   2019      8     12903              57        NaN   2019-08       -0.013004                NaN       -0.123077  Washington  United States        NaN  0.004418                 NaN         -0.111523
8   2019      9     13282              56        NaN   2019-09        0.029373                NaN       -0.017544  Washington  United States        NaN  0.004216                 NaN         -0.045578
9   2019     10     14721              64        NaN   2019-10        0.108342                NaN        0.142857  Washington  United States        NaN  0.004348                 NaN          0.031141
10  2019     11     13840              57        NaN   2019-11       -0.059846                NaN       -0.109375  Washington  United States        NaN  0.004118                 NaN         -0.052681
11  2019     12     14086              74        NaN   2019-12        0.017775                NaN        0.298246  Washington  United States        NaN  0.005253                 NaN          0.275573
12  2020      1     14035              58        NaN   2020-01       -0.003621                NaN       -0.216216  Washington  United States        NaN  0.004133                 NaN         -0.213368
13  2020      2     11775              36        NaN   2020-02       -0.161026                NaN       -0.379310  Washington  United States        NaN  0.003057                 NaN         -0.260180
14  2020      3      8505              46        NaN   2020-03       -0.277707                NaN        0.277778  Washington  United States        NaN  0.005409                 NaN          0.769057
15  2020      4      5287              58        NaN   2020-04       -0.378366                NaN        0.260870  Washington  United States        NaN  0.010970                 NaN          1.028314
16  2020      5      6268              43        NaN   2020-05        0.185549                NaN       -0.258621  Washington  United States        NaN  0.006860                 NaN         -0.374653

## MonthYear

In [28]:
dataSubMonthYear = data[['Month', 'Year','Crash_ID','Crash_Fatal_Fl','Death_Cnt','yearMonth']].sort_values(by=['Month', 'Year'])

In [29]:
dataSubMonthYear['crashPctChange'] = dataSubMonthYear.groupby('Month')['Crash_ID'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['deathCntPctChange'] = dataSubMonthYear.groupby('Month')['Death_Cnt'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatalPctChange'] = dataSubMonthYear.groupby('Month')['Crash_Fatal_Fl'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['State']='Washington'
dataSubMonthYear['Country']='United States'

In [30]:
dataSubMonthYear['deathRate']=dataSubMonthYear['Death_Cnt']/dataSubMonthYear['Crash_ID']
dataSubMonthYear['fatRate']=dataSubMonthYear['Crash_Fatal_Fl']/dataSubMonthYear['Crash_ID']

In [31]:
dataSubMonthYear['deathRatePctChange'] = dataSubMonthYear.groupby('Month')['deathRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatRatePctChange'] = dataSubMonthYear.groupby('Month')['fatRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))

In [32]:
with open("WA_dataSubMonthYear.csv",'w',newline='') as outputfile:
    dataSubMonthYear.to_csv(outputfile, header=True, index = False)

In [33]:
datacheck = pd.read_csv('WA_dataSubMonthYear.csv')
datacheck.shape

(17, 15)

#### The december tied data
In this section we compare the all the months we have in 2020 to the most recent "normal month" which is December.

In [34]:
compare = dataSubYearMonth[['yearMonth', 'Crash_ID', 'Crash_Fatal_Fl']][dataSubYearMonth.yearMonth >= '2019-12']

compare['crashPctChangeCompareDec'] = compare.Crash_ID / compare.Crash_ID.iloc[0] - 1
compare['fatalPctChangeCompareDec'] = compare.Crash_Fatal_Fl / compare.Crash_Fatal_Fl.iloc[0] - 1

compare['State']='Washington'
compare['Country']='United States'

In [35]:
compare

   yearMonth  Crash_ID  Crash_Fatal_Fl  crashPctChangeCompareDec  fatalPctChangeCompareDec       State        Country
11   2019-12     14086              74                  0.000000                  0.000000  Washington  United States
12   2020-01     14035              58                 -0.003621                 -0.216216  Washington  United States
13   2020-02     11775              36                 -0.164064                 -0.513514  Washington  United States
14   2020-03      8505              46                 -0.396209                 -0.378378  Washington  United States
15   2020-04      5287              58                 -0.624663                 -0.216216  Washington  United States
16   2020-05      6268              43                 -0.555019                 -0.418919  Washington  United States

In [36]:
with open("WA_PctChangeCompareDec.csv",'w',newline='') as outputfile:
    compare.to_csv(outputfile, header=True, index = False)