In [21]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import datetime as dt
import warnings
warnings.filterwarnings("ignore")

In [22]:
data = pd.read_csv("Vermont.csv")

In [23]:
data.head()

   Year  Month  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth
0  2019      1      1724               2        NaN   2019-01
1  2019      2      1088               0        NaN   2019-02
2  2019      3      1095               2        NaN   2019-03
3  2019      4       831               1        NaN   2019-04
4  2019      5       894               2        NaN   2019-05

## YearMonth

In [24]:
dataSubYearMonth = data.copy()

In [25]:
dataSubYearMonth['crashPctChange'] = dataSubYearMonth.Crash_ID.pct_change()
dataSubYearMonth['deathCntPctChange'] = dataSubYearMonth.Death_Cnt.pct_change()
dataSubYearMonth['fatalPctChange'] = dataSubYearMonth.Crash_Fatal_Fl.pct_change()
dataSubYearMonth['State']='Vermont'
dataSubYearMonth['Country']='United States'

In [26]:
dataSubYearMonth['deathRate']=dataSubYearMonth['Death_Cnt']/dataSubYearMonth['Crash_ID']
dataSubYearMonth['fatRate']=dataSubYearMonth['Crash_Fatal_Fl']/dataSubYearMonth['Crash_ID']

In [27]:
dataSubYearMonth['deathRatePctChange'] = dataSubYearMonth.deathRate.pct_change()
dataSubYearMonth['fatRatePctChange'] = dataSubYearMonth.fatRate.pct_change()

In [28]:
with open("VT_dataSubYearMonth.csv",'w', newline='') as outputfile:
    dataSubYearMonth.to_csv(outputfile, header=True, index = False)

In [29]:
datacheck = pd.read_csv('VT_dataSubYearMonth.csv')

In [30]:
datacheck

    Year  Month  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth  crashPctChange  deathCntPctChange  fatalPctChange    State        Country  deathRate   fatRate  deathRatePctChange  fatRatePctChange
0   2019      1      1724               2        NaN   2019-01             NaN                NaN             NaN  Vermont  United States        NaN  0.001160                 NaN               NaN
1   2019      2      1088               0        NaN   2019-02       -0.368910                NaN       -1.000000  Vermont  United States        NaN  0.000000                 NaN         -1.000000
2   2019      3      1095               2        NaN   2019-03        0.006434                NaN             inf  Vermont  United States        NaN  0.001826                 NaN               inf
3   2019      4       831               1        NaN   2019-04       -0.241096                NaN       -0.500000  Vermont  United States        NaN  0.001203                 NaN         -0.341155
4   2019      5       894               2        NaN   2019-05        0.075812                NaN        1.000000  Vermont  United States        NaN  0.002237                 NaN          0.859060
5   2019      6      1014               4        NaN   2019-06        0.134228                NaN        1.000000  Vermont  United States        NaN  0.003945                 NaN          0.763314
6   2019      7      1081               2        NaN   2019-07        0.066075                NaN       -0.500000  Vermont  United States        NaN  0.001850                 NaN         -0.530990
7   2019      8      1071               7        NaN   2019-08       -0.009251                NaN        2.500000  Vermont  United States        NaN  0.006536                 NaN          2.532680
8   2019      9       966               4        NaN   2019-09       -0.098039                NaN       -0.428571  Vermont  United States        NaN  0.004141                 NaN         -0.366460
9   2019     10      1007               9        NaN   2019-10        0.042443                NaN        1.250000  Vermont  United States        NaN  0.008937                 NaN          1.158391
10  2019     11      1278               4        NaN   2019-11        0.269116                NaN       -0.555556  Vermont  United States        NaN  0.003130                 NaN         -0.649800
11  2019     12       893               7        NaN   2019-12       -0.301252                NaN        0.750000  Vermont  United States        NaN  0.007839                 NaN          1.504479
12  2020      1      1384               3        NaN   2020-01        0.549832                NaN       -0.571429  Vermont  United States        NaN  0.002168                 NaN         -0.723472
13  2020      2      1240               1        NaN   2020-02       -0.104046                NaN       -0.666667  Vermont  United States        NaN  0.000806                 NaN         -0.627957
14  2020      3       633               2        NaN   2020-03       -0.489516                NaN        1.000000  Vermont  United States        NaN  0.003160                 NaN          2.917852
15  2020      4       312               1        NaN   2020-04       -0.507109                NaN       -0.500000  Vermont  United States        NaN  0.003205                 NaN          0.014423

## MonthYear

In [31]:
dataSubMonthYear = data[['Month', 'Year','Crash_ID','Crash_Fatal_Fl','Death_Cnt','yearMonth']].sort_values(by=['Month', 'Year'])

In [32]:
dataSubMonthYear['crashPctChange'] = dataSubMonthYear.groupby('Month')['Crash_ID'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['deathCntPctChange'] = dataSubMonthYear.groupby('Month')['Death_Cnt'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatalPctChange'] = dataSubMonthYear.groupby('Month')['Crash_Fatal_Fl'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['State']='Vermont'
dataSubMonthYear['Country']='United States'

In [33]:
dataSubMonthYear['deathRate']=dataSubMonthYear['Death_Cnt']/dataSubMonthYear['Crash_ID']
dataSubMonthYear['fatRate']=dataSubMonthYear['Crash_Fatal_Fl']/dataSubMonthYear['Crash_ID']

In [34]:
dataSubMonthYear['deathRatePctChange'] = dataSubMonthYear.groupby('Month')['deathRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatRatePctChange'] = dataSubMonthYear.groupby('Month')['fatRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))

In [35]:
with open("VT_dataSubMonthYear.csv",'w', newline='') as outputfile:
    dataSubMonthYear.to_csv(outputfile, header=True, index = False)

In [36]:
datacheck = pd.read_csv('VT_dataSubMonthYear.csv')
datacheck.shape

(16, 15)

In [37]:
datacheck

    Month  Year  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth  crashPctChange  deathCntPctChange  fatalPctChange    State        Country  deathRate   fatRate  deathRatePctChange  fatRatePctChange
0       1  2019      1724               2        NaN   2019-01        0.000000                NaN             0.0  Vermont  United States        NaN  0.001160                 NaN          0.000000
1       1  2020      1384               3        NaN   2020-01       -0.197216                NaN             0.5  Vermont  United States        NaN  0.002168                 NaN          0.868497
2       2  2019      1088               0        NaN   2019-02        0.000000                NaN             NaN  Vermont  United States        NaN  0.000000                 NaN               NaN
3       2  2020      1240               1        NaN   2020-02        0.139706                NaN             inf  Vermont  United States        NaN  0.000806                 NaN               inf
4       3  2019      1095               2        NaN   2019-03        0.000000                NaN             0.0  Vermont  United States        NaN  0.001826                 NaN          0.000000
5       3  2020       633               2        NaN   2020-03       -0.421918                NaN             0.0  Vermont  United States        NaN  0.003160                 NaN          0.729858
6       4  2019       831               1        NaN   2019-04        0.000000                NaN             0.0  Vermont  United States        NaN  0.001203                 NaN          0.000000
7       4  2020       312               1        NaN   2020-04       -0.624549                NaN             0.0  Vermont  United States        NaN  0.003205                 NaN          1.663462
8       5  2019       894               2        NaN   2019-05        0.000000                NaN             0.0  Vermont  United States        NaN  0.002237                 NaN          0.000000
9       6  2019      1014               4        NaN   2019-06        0.000000                NaN             0.0  Vermont  United States        NaN  0.003945                 NaN          0.000000
10      7  2019      1081               2        NaN   2019-07        0.000000                NaN             0.0  Vermont  United States        NaN  0.001850                 NaN          0.000000
11      8  2019      1071               7        NaN   2019-08        0.000000                NaN             0.0  Vermont  United States        NaN  0.006536                 NaN          0.000000
12      9  2019       966               4        NaN   2019-09        0.000000                NaN             0.0  Vermont  United States        NaN  0.004141                 NaN          0.000000
13     10  2019      1007               9        NaN   2019-10        0.000000                NaN             0.0  Vermont  United States        NaN  0.008937                 NaN          0.000000
14     11  2019      1278               4        NaN   2019-11        0.000000                NaN             0.0  Vermont  United States        NaN  0.003130                 NaN          0.000000
15     12  2019       893               7        NaN   2019-12        0.000000                NaN             0.0  Vermont  United States        NaN  0.007839                 NaN          0.000000

#### The december tied data
In this section we compare the all the months we have in 2020 to the most recent "normal month" which is December.

In [38]:
compare = dataSubYearMonth[['yearMonth', 'Crash_ID', 'Crash_Fatal_Fl']][dataSubYearMonth.yearMonth >= '2019-12']

compare['crashPctChangeCompareDec'] = compare.Crash_ID / compare.Crash_ID.iloc[0] - 1
compare['fatalPctChangeCompareDec'] = compare.Crash_Fatal_Fl / compare.Crash_Fatal_Fl.iloc[0] - 1

compare['State']='Vermont'
compare['Country']='United States'

In [39]:
compare

   yearMonth  Crash_ID  Crash_Fatal_Fl  crashPctChangeCompareDec  fatalPctChangeCompareDec    State        Country
11   2019-12       893               7                  0.000000                  0.000000  Vermont  United States
12   2020-01      1384               3                  0.549832                 -0.571429  Vermont  United States
13   2020-02      1240               1                  0.388578                 -0.857143  Vermont  United States
14   2020-03       633               2                 -0.291153                 -0.714286  Vermont  United States
15   2020-04       312               1                 -0.650616                 -0.857143  Vermont  United States

In [40]:
with open("VT_PctChangeCompareDec.csv",'w', newline='') as outputfile:
    compare.to_csv(outputfile, header=True, index = False)