In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import datetime as dt
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("Iowa.csv")

## YearMonth

In [3]:
dataSubYearMonth = data.copy()

In [4]:
dataSubYearMonth['crashPctChange'] = dataSubYearMonth.Crash_ID.pct_change()
dataSubYearMonth['deathCntPctChange'] = dataSubYearMonth.Death_Cnt.pct_change()
dataSubYearMonth['fatalPctChange'] = dataSubYearMonth.Crash_Fatal_Fl.pct_change()
dataSubYearMonth['State']='Iowa'
dataSubYearMonth['Country']='United States'

In [5]:
dataSubYearMonth['deathRate']=dataSubYearMonth['Death_Cnt']/dataSubYearMonth['Crash_ID']
dataSubYearMonth['fatRate']=dataSubYearMonth['Crash_Fatal_Fl']/dataSubYearMonth['Crash_ID']

In [6]:
dataSubYearMonth['deathRatePctChange'] = dataSubYearMonth.deathRate.pct_change()
dataSubYearMonth['fatRatePctChange'] = dataSubYearMonth.fatRate.pct_change()

In [7]:
with open("IA_dataSubYearMonth.csv",'w', newline='') as outputfile:
    dataSubYearMonth.to_csv(outputfile, header=True, index = False)

In [8]:
datacheck = pd.read_csv('IA_dataSubYearMonth.csv')

In [9]:
datacheck

    Year  Month  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth  crashPctChange  deathCntPctChange  fatalPctChange State        Country  deathRate   fatRate  deathRatePctChange  fatRatePctChange
0   2019      1      5621              19         21   2019-01             NaN                NaN             NaN  Iowa  United States   0.003736  0.003380                 NaN               NaN
1   2019      2      5872              17         20   2019-02        0.044654          -0.047619       -0.105263  Iowa  United States   0.003406  0.002895           -0.088329         -0.143509
2   2019      3      4031              18         22   2019-03       -0.313522           0.100000        0.058824  Iowa  United States   0.005458  0.004465            0.602382          0.542399
3   2019      4      4031              21         22   2019-04        0.000000           0.000000        0.166667  Iowa  United States   0.005458  0.005210            0.000000          0.166667
4   2019      5      4504              27         30   2019-05        0.117341           0.363636        0.285714  Iowa  United States   0.006661  0.005995            0.220430          0.150691
5   2019      6      4604              34         35   2019-06        0.022202           0.166667        0.259259  Iowa  United States   0.007602  0.007385            0.141326          0.231908
6   2019      7      4345              28         32   2019-07       -0.056255          -0.085714       -0.176471  Iowa  United States   0.007365  0.006444           -0.031215         -0.127381
7   2019      8      4295              30         31   2019-08       -0.011507          -0.031250        0.071429  Iowa  United States   0.007218  0.006985           -0.019972          0.083902
8   2019      9      4438              39         39   2019-09        0.033295           0.258065        0.300000  Iowa  United States   0.008788  0.008788            0.217528          0.258112
9   2019     10      5431              21         21   2019-10        0.223749          -0.461538       -0.461538  Iowa  United States   0.003867  0.003867           -0.559990         -0.559990
10  2019     11      5956              32         35   2019-11        0.096667           0.666667        0.523810  Iowa  United States   0.005876  0.005373            0.519756          0.389491
11  2019     12      5126              27         28   2019-12       -0.139355          -0.200000       -0.156250  Iowa  United States   0.005462  0.005267           -0.070464         -0.019630
12  2020      1      5189              22         24   2020-01        0.012290          -0.142857       -0.185185  Iowa  United States   0.004625  0.004240           -0.153264         -0.195078
13  2020      2      3723              15         17   2020-02       -0.282521          -0.291667       -0.318182  Iowa  United States   0.004566  0.004029           -0.012747         -0.049703
14  2020      3      2935              12         13   2020-03       -0.211657          -0.235294       -0.200000  Iowa  United States   0.004429  0.004089           -0.029983          0.014787
15  2020      4      2335              16         17   2020-04       -0.204429           0.307692        0.333333  Iowa  United States   0.007281  0.006852            0.643716          0.675946
16  2020      5      2818              16         17   2020-05        0.206852           0.000000        0.000000  Iowa  United States   0.006033  0.005678           -0.171398         -0.171398

## MonthYear

In [10]:
dataSubMonthYear = data[['Month', 'Year','Crash_ID','Crash_Fatal_Fl','Death_Cnt','yearMonth']].sort_values(by=['Month', 'Year'])

In [11]:
dataSubMonthYear['crashPctChange'] = dataSubMonthYear.groupby('Month')['Crash_ID'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['deathCntPctChange'] = dataSubMonthYear.groupby('Month')['Death_Cnt'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatalPctChange'] = dataSubMonthYear.groupby('Month')['Crash_Fatal_Fl'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['State']='Iowa'
dataSubMonthYear['Country']='United States'

In [12]:
dataSubMonthYear['deathRate']=dataSubMonthYear['Death_Cnt']/dataSubMonthYear['Crash_ID']
dataSubMonthYear['fatRate']=dataSubMonthYear['Crash_Fatal_Fl']/dataSubMonthYear['Crash_ID']

In [13]:
dataSubMonthYear['deathRatePctChange'] = dataSubMonthYear.groupby('Month')['deathRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatRatePctChange'] = dataSubMonthYear.groupby('Month')['fatRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))

In [14]:
with open("IA_dataSubMonthYear.csv",'w',newline='') as outputfile:
    dataSubMonthYear.to_csv(outputfile, header=True, index = False)

In [15]:
datacheck = pd.read_csv('IA_dataSubMonthYear.csv')
datacheck.shape

(17, 15)

#### The december tied data
In this section we compare the all the months we have in 2020 to the most recent "normal month" which is December.

In [16]:
compare = dataSubYearMonth[['yearMonth', 'Crash_ID', 'Crash_Fatal_Fl']][dataSubYearMonth.yearMonth >= '2019-12']

compare['crashPctChangeCompareDec'] = compare.Crash_ID / compare.Crash_ID.iloc[0] - 1
compare['fatalPctChangeCompareDec'] = compare.Crash_Fatal_Fl / compare.Crash_Fatal_Fl.iloc[0] - 1

compare['State']='Iowa'
compare['Country']='United States'

In [17]:
compare

   yearMonth  Crash_ID  Crash_Fatal_Fl  crashPctChangeCompareDec  fatalPctChangeCompareDec State        Country
11   2019-12      5126              27                  0.000000                  0.000000  Iowa  United States
12   2020-01      5189              22                  0.012290                 -0.185185  Iowa  United States
13   2020-02      3723              15                 -0.273703                 -0.444444  Iowa  United States
14   2020-03      2935              12                 -0.427429                 -0.555556  Iowa  United States
15   2020-04      2335              16                 -0.544479                 -0.407407  Iowa  United States
16   2020-05      2818              16                 -0.450254                 -0.407407  Iowa  United States

In [18]:
with open("IA_PctChangeCompareDec.csv",'w',newline='') as outputfile:
    compare.to_csv(outputfile, header=True, index = False)