In [9]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import datetime as dt
import warnings
warnings.filterwarnings("ignore")

In [10]:
data = pd.read_csv("Missouri.csv")

## YearMonth

In [11]:
dataSubYearMonth = data.copy()

In [12]:
dataSubYearMonth['crashPctChange'] = dataSubYearMonth.Crash_ID.pct_change()
dataSubYearMonth['deathCntPctChange'] = dataSubYearMonth.Death_Cnt.pct_change()
dataSubYearMonth['fatalPctChange'] = dataSubYearMonth.Crash_Fatal_Fl.pct_change()
dataSubYearMonth['State']='Missouri'
dataSubYearMonth['Country']='United States'

In [13]:
dataSubYearMonth['deathRate']=dataSubYearMonth['Death_Cnt']/dataSubYearMonth['Crash_ID']
dataSubYearMonth['fatRate']=dataSubYearMonth['Crash_Fatal_Fl']/dataSubYearMonth['Crash_ID']

In [14]:
dataSubYearMonth['deathRatePctChange'] = dataSubYearMonth.deathRate.pct_change()
dataSubYearMonth['fatRatePctChange'] = dataSubYearMonth.fatRate.pct_change()

In [15]:
with open("MO_May_dataSubYearMonth.csv",'w', newline='') as outputfile:
    dataSubYearMonth.to_csv(outputfile, header=True, index = False)

In [16]:
datacheck = pd.read_csv('MO_May_dataSubYearMonth.csv')

In [17]:
datacheck

    Year  Month  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth  crashPctChange  deathCntPctChange  fatalPctChange     State        Country  deathRate   fatRate  deathRatePctChange  fatRatePctChange
0   2019      1     12664              55        NaN   2019-01             NaN                NaN             NaN  Missouri  United States        NaN  0.004343                 NaN               NaN
1   2019      2     12580              51        NaN   2019-02       -0.006633                NaN       -0.072727  Missouri  United States        NaN  0.004054                 NaN         -0.066536
2   2019      3     11404              47        NaN   2019-03       -0.093482                NaN       -0.078431  Missouri  United States        NaN  0.004121                 NaN          0.016602
3   2019      4     12218              60        NaN   2019-04        0.071378                NaN        0.276596  Missouri  United States        NaN  0.004911                 NaN          0.191545
4   2019      5     13200              58        NaN   2019-05        0.080373                NaN       -0.033333  Missouri  United States        NaN  0.004394                 NaN         -0.105247
5   2019      6     13063              81        NaN   2019-06       -0.010379                NaN        0.396552  Missouri  United States        NaN  0.006201                 NaN          0.411198
6   2019      7     11739              84        NaN   2019-07       -0.101355                NaN        0.037037  Missouri  United States        NaN  0.007156                 NaN          0.154001
7   2019      8      1019              92        NaN   2019-08       -0.913195                NaN        0.095238  Missouri  United States        NaN  0.090285                 NaN         11.617272
8   2019      9     11074              73        NaN   2019-09        9.867517                NaN       -0.206522  Missouri  United States        NaN  0.006592                 NaN         -0.926986
9   2019     10     12814              79        NaN   2019-10        0.157125                NaN        0.082192  Missouri  United States        NaN  0.006165                 NaN         -0.064758
10  2019     11     13551              71        NaN   2019-11        0.057515                NaN       -0.101266  Missouri  United States        NaN  0.005239                 NaN         -0.150145
11  2019     12     12817              66        NaN   2019-12       -0.054166                NaN       -0.070423  Missouri  United States        NaN  0.005149                 NaN         -0.017188
12  2020      1     10899              45        NaN   2020-01       -0.149645                NaN       -0.318182  Missouri  United States        NaN  0.004129                 NaN         -0.198196
13  2020      2      7105              64        NaN   2020-02       -0.348105                NaN        0.422222  Missouri  United States        NaN  0.009008                 NaN          1.181675
14  2020      3      1636              45        NaN   2020-03       -0.769740                NaN       -0.296875  Missouri  United States        NaN  0.027506                 NaN          2.053608
15  2020      4      1230              53        NaN   2020-04       -0.248166                NaN        0.177778  Missouri  United States        NaN  0.043089                 NaN          0.566540
16  2020      5      1310              53        NaN   2020-05        0.065041                NaN        0.000000  Missouri  United States        NaN  0.040458                 NaN         -0.061069

## MonthYear

In [18]:
dataSubMonthYear = data[['Month', 'Year','Crash_ID','Crash_Fatal_Fl','Death_Cnt','yearMonth']].sort_values(by=['Month', 'Year'])

In [19]:
dataSubMonthYear['crashPctChange'] = dataSubMonthYear.groupby('Month')['Crash_ID'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['deathCntPctChange'] = dataSubMonthYear.groupby('Month')['Death_Cnt'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatalPctChange'] = dataSubMonthYear.groupby('Month')['Crash_Fatal_Fl'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['State']='Missouri'
dataSubMonthYear['Country']='United States'

In [20]:
dataSubMonthYear['deathRate']=dataSubMonthYear['Death_Cnt']/dataSubMonthYear['Crash_ID']
dataSubMonthYear['fatRate']=dataSubMonthYear['Crash_Fatal_Fl']/dataSubMonthYear['Crash_ID']

In [21]:
dataSubMonthYear['deathRatePctChange'] = dataSubMonthYear.groupby('Month')['deathRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatRatePctChange'] = dataSubMonthYear.groupby('Month')['fatRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))

In [22]:
with open("MO_May_dataSubMonthYear.csv",'w',newline='') as outputfile:
    dataSubMonthYear.to_csv(outputfile, header=True, index = False)

In [23]:
datacheck = pd.read_csv('MO_May_dataSubMonthYear.csv')
datacheck.shape

(17, 15)

#### The december tied data
In this section we compare the all the months we have in 2020 to the most recent "normal month" which is December.

In [24]:
compare = dataSubYearMonth[['yearMonth', 'Crash_ID', 'Crash_Fatal_Fl']][dataSubYearMonth.yearMonth >= '2019-12']

compare['crashPctChangeCompareDec'] = compare.Crash_ID / compare.Crash_ID.iloc[0] - 1
compare['fatalPctChangeCompareDec'] = compare.Crash_Fatal_Fl / compare.Crash_Fatal_Fl.iloc[0] - 1

compare['State']='Missouri'
compare['Country']='United States'

In [25]:
compare

   yearMonth  Crash_ID  Crash_Fatal_Fl  crashPctChangeCompareDec  fatalPctChangeCompareDec     State        Country
11   2019-12     12817              66                  0.000000                  0.000000  Missouri  United States
12   2020-01     10899              45                 -0.149645                 -0.318182  Missouri  United States
13   2020-02      7105              64                 -0.445658                 -0.030303  Missouri  United States
14   2020-03      1636              45                 -0.872357                 -0.318182  Missouri  United States
15   2020-04      1230              53                 -0.904034                 -0.196970  Missouri  United States
16   2020-05      1310              53                 -0.897792                 -0.196970  Missouri  United States

In [26]:
with open("MO_May_PctChangeCompareDec.csv",'w',newline='') as outputfile:
    compare.to_csv(outputfile, header=True, index = False)