In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import datetime as dt
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("Florida.csv")

In [3]:
data.head()

   Year  Month  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth
0  2019      1     32852             238        257   2019-01
1  2019      2     32157             263        281   2019-02
2  2019      3     35910             305        334   2019-03
3  2019      4     33692             268        292   2019-04
4  2019      5     34645             255        264   2019-05

## YearMonth

In [4]:
dataSubYearMonth = data.copy()

In [5]:
dataSubYearMonth['crashPctChange'] = dataSubYearMonth.Crash_ID.pct_change()
dataSubYearMonth['deathCntPctChange'] = dataSubYearMonth.Death_Cnt.pct_change()
dataSubYearMonth['fatalPctChange'] = dataSubYearMonth.Crash_Fatal_Fl.pct_change()
dataSubYearMonth['State']='Florida'
dataSubYearMonth['Country']='United States'

In [6]:
dataSubYearMonth['deathRate']=dataSubYearMonth['Death_Cnt']/dataSubYearMonth['Crash_ID']
dataSubYearMonth['fatRate']=dataSubYearMonth['Crash_Fatal_Fl']/dataSubYearMonth['Crash_ID']

In [7]:
dataSubYearMonth['deathRatePctChange'] = dataSubYearMonth.deathRate.pct_change()
dataSubYearMonth['fatRatePctChange'] = dataSubYearMonth.fatRate.pct_change()

In [8]:
with open("FL_dataSubYearMonth.csv",'w') as outputfile:
    dataSubYearMonth.to_csv(outputfile, header=True, index = False)

In [9]:
datacheck = pd.read_csv('FL_dataSubYearMonth.csv')

In [10]:
datacheck

    Year  Month  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth  crashPctChange  deathCntPctChange  fatalPctChange    State        Country  deathRate   fatRate  deathRatePctChange  fatRatePctChange
0   2019      1     32852             238        257   2019-01             NaN                NaN             NaN  Florida  United States   0.007823  0.007245                 NaN               NaN
1   2019      2     32157             263        281   2019-02       -0.021155           0.093385        0.105042  Florida  United States   0.008738  0.008179            0.117016          0.128925
2   2019      3     35910             305        334   2019-03        0.116709           0.188612        0.159696  Florida  United States   0.009301  0.008493            0.064389          0.038495
3   2019      4     33692             268        292   2019-04       -0.061766          -0.125749       -0.121311  Florida  United States   0.008667  0.007954           -0.068195         -0.063466
4   2019      5     34645             255        264   2019-05        0.028286          -0.095890       -0.048507  Florida  United States   0.007620  0.007360           -0.120760         -0.074681
5   2019      6     31111             236        254   2019-06       -0.102006          -0.037879       -0.074510  Florida  United States   0.008164  0.007586            0.071412          0.030620
6   2019      7     31000             220        239   2019-07       -0.003568          -0.059055       -0.067797  Florida  United States   0.007710  0.007097           -0.055686         -0.064459
7   2019      8     34401             219        245   2019-08        0.109710           0.025105       -0.004545  Florida  United States   0.007122  0.006366           -0.076241         -0.102959
8   2019      9     30942             229        246   2019-09       -0.100549           0.004082        0.045662  Florida  United States   0.007950  0.007401            0.116328          0.162556
9   2019     10     35527             220        236   2019-10        0.148180          -0.040650       -0.039301  Florida  United States   0.006643  0.006192           -0.164461         -0.163286
10  2019     11     32660             280        308   2019-11       -0.080699           0.305085        0.272727  Florida  United States   0.009430  0.008573            0.419649          0.384451
11  2019     12     35670             237        259   2019-12        0.092162          -0.159091       -0.153571  Florida  United States   0.007261  0.006644           -0.230051         -0.224997
12  2020      1     32483             272        283   2020-01       -0.089347           0.092664        0.147679  Florida  United States   0.008712  0.008374            0.199868          0.260281
13  2020      2     31768             249        270   2020-02       -0.022012          -0.045936       -0.084559  Florida  United States   0.008499  0.007838           -0.024463         -0.063955
14  2020      3     26840             250        265   2020-03       -0.155125          -0.018519        0.004016  Florida  United States   0.009873  0.009314            0.161688          0.188360
15  2020      4     16191             185        205   2020-04       -0.396759          -0.226415       -0.260000  Florida  United States   0.012661  0.011426            0.282380          0.226706

## MonthYear

In [11]:
dataSubMonthYear = data[['Month', 'Year','Crash_ID','Crash_Fatal_Fl','Death_Cnt','yearMonth']].sort_values(by=['Month', 'Year'])

In [12]:
dataSubMonthYear['crashPctChange'] = dataSubMonthYear.groupby('Month')['Crash_ID'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['deathCntPctChange'] = dataSubMonthYear.groupby('Month')['Death_Cnt'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatalPctChange'] = dataSubMonthYear.groupby('Month')['Crash_Fatal_Fl'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['State']='Florida'
dataSubMonthYear['Country']='United States'

In [13]:
dataSubMonthYear['deathRate']=dataSubMonthYear['Death_Cnt']/dataSubMonthYear['Crash_ID']
dataSubMonthYear['fatRate']=dataSubMonthYear['Crash_Fatal_Fl']/dataSubMonthYear['Crash_ID']

In [14]:
dataSubMonthYear['deathRatePctChange'] = dataSubMonthYear.groupby('Month')['deathRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatRatePctChange'] = dataSubMonthYear.groupby('Month')['fatRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))

In [15]:
with open("FL_dataSubMonthYear.csv",'w') as outputfile:
    dataSubMonthYear.to_csv(outputfile, header=True, index = False)

In [16]:
datacheck = pd.read_csv('FL_dataSubMonthYear.csv')
datacheck.shape

(16, 15)

In [17]:
datacheck

    Month  Year  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth  crashPctChange  deathCntPctChange  fatalPctChange    State        Country  deathRate   fatRate  deathRatePctChange  fatRatePctChange
0       1  2019     32852             238        257   2019-01        0.000000           0.000000        0.000000  Florida  United States   0.007823  0.007245            0.000000          0.000000
1       1  2020     32483             272        283   2020-01       -0.011232           0.101167        0.142857  Florida  United States   0.008712  0.008374            0.113676          0.155840
2       2  2019     32157             263        281   2019-02        0.000000           0.000000        0.000000  Florida  United States   0.008738  0.008179            0.000000          0.000000
3       2  2020     31768             249        270   2020-02       -0.012097          -0.039146       -0.053232  Florida  United States   0.008499  0.007838           -0.027380         -0.041639
4       3  2019     35910             305        334   2019-03        0.000000           0.000000        0.000000  Florida  United States   0.009301  0.008493            0.000000          0.000000
5       3  2020     26840             250        265   2020-03       -0.252576          -0.206587       -0.180328  Florida  United States   0.009873  0.009314            0.061530          0.096663
6       4  2019     33692             268        292   2019-04        0.000000           0.000000        0.000000  Florida  United States   0.008667  0.007954            0.000000          0.000000
7       4  2020     16191             185        205   2020-04       -0.519441          -0.297945       -0.309701  Florida  United States   0.012661  0.011426            0.460912          0.436448
8       5  2019     34645             255        264   2019-05        0.000000           0.000000        0.000000  Florida  United States   0.007620  0.007360            0.000000          0.000000
9       6  2019     31111             236        254   2019-06        0.000000           0.000000        0.000000  Florida  United States   0.008164  0.007586            0.000000          0.000000
10      7  2019     31000             220        239   2019-07        0.000000           0.000000        0.000000  Florida  United States   0.007710  0.007097            0.000000          0.000000
11      8  2019     34401             219        245   2019-08        0.000000           0.000000        0.000000  Florida  United States   0.007122  0.006366            0.000000          0.000000
12      9  2019     30942             229        246   2019-09        0.000000           0.000000        0.000000  Florida  United States   0.007950  0.007401            0.000000          0.000000
13     10  2019     35527             220        236   2019-10        0.000000           0.000000        0.000000  Florida  United States   0.006643  0.006192            0.000000          0.000000
14     11  2019     32660             280        308   2019-11        0.000000           0.000000        0.000000  Florida  United States   0.009430  0.008573            0.000000          0.000000
15     12  2019     35670             237        259   2019-12        0.000000           0.000000        0.000000  Florida  United States   0.007261  0.006644            0.000000          0.000000

#### The december tied data
In this section we compare the all the months we have in 2020 to the most recent "normal month" which is December.

In [18]:
compare = dataSubYearMonth[['yearMonth', 'Crash_ID', 'Crash_Fatal_Fl']][dataSubYearMonth.yearMonth >= '2019-12']

compare['crashPctChangeCompareDec'] = compare.Crash_ID / compare.Crash_ID.iloc[0] - 1
compare['fatalPctChangeCompareDec'] = compare.Crash_Fatal_Fl / compare.Crash_Fatal_Fl.iloc[0] - 1

compare['State']='Florida'
compare['Country']='United States'

In [19]:
compare

   yearMonth  Crash_ID  Crash_Fatal_Fl  crashPctChangeCompareDec  fatalPctChangeCompareDec    State        Country
11   2019-12     35670             237                  0.000000                  0.000000  Florida  United States
12   2020-01     32483             272                 -0.089347                  0.147679  Florida  United States
13   2020-02     31768             249                 -0.109392                  0.050633  Florida  United States
14   2020-03     26840             250                 -0.247547                  0.054852  Florida  United States
15   2020-04     16191             185                 -0.546089                 -0.219409  Florida  United States

In [20]:
with open("FL_PctChangeCompareDec.csv",'w') as outputfile:
    compare.to_csv(outputfile, header=True, index = False)