In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import datetime as dt
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("Utah.csv")

## YearMonth

In [3]:
dataSubYearMonth = data.copy()

In [4]:
dataSubYearMonth['crashPctChange'] = dataSubYearMonth.Crash_ID.pct_change()
dataSubYearMonth['deathCntPctChange'] = dataSubYearMonth.Death_Cnt.pct_change()
dataSubYearMonth['fatalPctChange'] = dataSubYearMonth.Crash_Fatal_Fl.pct_change()
dataSubYearMonth['State']='Utah'
dataSubYearMonth['Country']='United States'

In [5]:
dataSubYearMonth['deathRate']=dataSubYearMonth['Death_Cnt']/dataSubYearMonth['Crash_ID']
dataSubYearMonth['fatRate']=dataSubYearMonth['Crash_Fatal_Fl']/dataSubYearMonth['Crash_ID']

In [6]:
dataSubYearMonth['deathRatePctChange'] = dataSubYearMonth.deathRate.pct_change()
dataSubYearMonth['fatRatePctChange'] = dataSubYearMonth.fatRate.pct_change()

In [7]:
with open("UT_dataSubYearMonth.csv",'w', newline='') as outputfile:
    dataSubYearMonth.to_csv(outputfile, header=True, index = False)

In [8]:
datacheck = pd.read_csv('UT_dataSubYearMonth.csv')

In [9]:
datacheck

    Year  Month  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth  crashPctChange  deathCntPctChange  fatalPctChange State        Country  deathRate   fatRate  deathRatePctChange  fatRatePctChange
0   2019      1      5600              14         15   2019-01             NaN                NaN             NaN  Utah  United States   0.002679  0.002500                 NaN               NaN
1   2019      2      5618              11         11   2019-02        0.003214          -0.266667       -0.214286  Utah  United States   0.001958  0.001958           -0.269016         -0.216803
2   2019      3      5387              19         22   2019-03       -0.041118           1.000000        0.727273  Utah  United States   0.004084  0.003527            1.085762          0.801340
3   2019      4      5299              16         17   2019-04       -0.016336          -0.227273       -0.157895  Utah  United States   0.003208  0.003019           -0.214440         -0.143910
4   2019      5      5864              22         24   2019-05        0.106624           0.411765        0.375000  Utah  United States   0.004093  0.003752            0.275740          0.242518
5   2019      6      5281              15         15   2019-06       -0.099420          -0.375000       -0.318182  Utah  United States   0.002840  0.002840           -0.306003         -0.242912
6   2019      7      4914              19         21   2019-07       -0.069494           0.400000        0.266667  Utah  United States   0.004274  0.003867            0.504558          0.361267
7   2019      8      5548              20         23   2019-08        0.129019           0.095238        0.052632  Utah  United States   0.004146  0.003605           -0.029921         -0.067658
8   2019      9      5808              25         28   2019-09        0.046864           0.217391        0.250000  Utah  United States   0.004821  0.004304            0.162894          0.194043
9   2019     10      5752              17         21   2019-10       -0.009642          -0.250000       -0.320000  Utah  United States   0.003651  0.002955           -0.242698         -0.313380
10  2019     11      5996              27         29   2019-11        0.042420           0.380952        0.588235  Utah  United States   0.004837  0.004503            0.324756          0.523604
11  2019     12      5521              19         22   2019-12       -0.079219          -0.241379       -0.296296  Utah  United States   0.003985  0.003441           -0.176111         -0.235753
12  2020      1      5562              12         14   2020-01        0.007426          -0.363636       -0.368421  Utah  United States   0.002517  0.002157           -0.368327         -0.373077
13  2020      2      5260              17         18   2020-02       -0.054297           0.285714        0.416667  Utah  United States   0.003422  0.003232            0.359533          0.498004
14  2020      3      3893              14         15   2020-03       -0.259886          -0.166667       -0.176471  Utah  United States   0.003853  0.003596            0.125953          0.112706
15  2020      4      2698              20         20   2020-04       -0.306961           0.333333        0.428571  Utah  United States   0.007413  0.007413            0.923894          1.061315
16  2020      5      3481              28         29   2020-05        0.290215           0.450000        0.400000  Utah  United States   0.008331  0.008044            0.123844          0.085090

## MonthYear

In [10]:
dataSubMonthYear = data[['Month', 'Year','Crash_ID','Crash_Fatal_Fl','Death_Cnt','yearMonth']].sort_values(by=['Month', 'Year'])

In [11]:
dataSubMonthYear['crashPctChange'] = dataSubMonthYear.groupby('Month')['Crash_ID'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['deathCntPctChange'] = dataSubMonthYear.groupby('Month')['Death_Cnt'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatalPctChange'] = dataSubMonthYear.groupby('Month')['Crash_Fatal_Fl'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['State']='Utah'
dataSubMonthYear['Country']='United States'

In [12]:
dataSubMonthYear['deathRate']=dataSubMonthYear['Death_Cnt']/dataSubMonthYear['Crash_ID']
dataSubMonthYear['fatRate']=dataSubMonthYear['Crash_Fatal_Fl']/dataSubMonthYear['Crash_ID']

In [13]:
dataSubMonthYear['deathRatePctChange'] = dataSubMonthYear.groupby('Month')['deathRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatRatePctChange'] = dataSubMonthYear.groupby('Month')['fatRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))

In [14]:
with open("UT_dataSubMonthYear.csv",'w',newline='') as outputfile:
    dataSubMonthYear.to_csv(outputfile, header=True, index = False)

In [16]:
datacheck = pd.read_csv('UT_dataSubMonthYear.csv')
datacheck.shape

(17, 15)

#### The december tied data
In this section we compare the all the months we have in 2020 to the most recent "normal month" which is December.

In [17]:
compare = dataSubYearMonth[['yearMonth', 'Crash_ID', 'Crash_Fatal_Fl']][dataSubYearMonth.yearMonth >= '2019-12']

compare['crashPctChangeCompareDec'] = compare.Crash_ID / compare.Crash_ID.iloc[0] - 1
compare['fatalPctChangeCompareDec'] = compare.Crash_Fatal_Fl / compare.Crash_Fatal_Fl.iloc[0] - 1

compare['State']='Utah'
compare['Country']='United States'

In [18]:
compare

   yearMonth  Crash_ID  Crash_Fatal_Fl  crashPctChangeCompareDec  fatalPctChangeCompareDec State        Country
11   2019-12      5521              19                  0.000000                  0.000000  Utah  United States
12   2020-01      5562              12                  0.007426                 -0.368421  Utah  United States
13   2020-02      5260              17                 -0.047274                 -0.105263  Utah  United States
14   2020-03      3893              14                 -0.294874                 -0.263158  Utah  United States
15   2020-04      2698              20                 -0.511320                  0.052632  Utah  United States
16   2020-05      3481              28                 -0.369498                  0.473684  Utah  United States

In [19]:
with open("UT_PctChangeCompareDec.csv",'w',newline='') as outputfile:
    compare.to_csv(outputfile, header=True, index = False)