In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import datetime as dt
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("Virginia.csv")

In [3]:
data.head()

   Year  Month  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth
0  2019      1      9891              66        NaN   2019-01
1  2019      2      9295              58        NaN   2019-02
2  2019      3     10200              60        NaN   2019-03
3  2019      4     10138              61        NaN   2019-04
4  2019      5     11178              74        NaN   2019-05

## YearMonth

In [4]:
dataSubYearMonth = data.copy()

In [5]:
dataSubYearMonth['crashPctChange'] = dataSubYearMonth.Crash_ID.pct_change()
dataSubYearMonth['deathCntPctChange'] = dataSubYearMonth.Death_Cnt.pct_change()
dataSubYearMonth['fatalPctChange'] = dataSubYearMonth.Crash_Fatal_Fl.pct_change()
dataSubYearMonth['State']='Virginia'
dataSubYearMonth['Country']='United States'

In [6]:
dataSubYearMonth['deathRate']=dataSubYearMonth['Death_Cnt']/dataSubYearMonth['Crash_ID']
dataSubYearMonth['fatRate']=dataSubYearMonth['Crash_Fatal_Fl']/dataSubYearMonth['Crash_ID']

In [7]:
dataSubYearMonth['deathRatePctChange'] = dataSubYearMonth.deathRate.pct_change()
dataSubYearMonth['fatRatePctChange'] = dataSubYearMonth.fatRate.pct_change()

In [8]:
with open("VA_dataSubYearMonth.csv",'w',newline='') as outputfile:
    dataSubYearMonth.to_csv(outputfile, header=True, index = False)

In [9]:
datacheck = pd.read_csv('VA_dataSubYearMonth.csv')

In [10]:
datacheck

    Year  Month  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth  crashPctChange  deathCntPctChange  fatalPctChange     State        Country  deathRate   fatRate  deathRatePctChange  fatRatePctChange
0   2019      1      9891              66        NaN   2019-01             NaN                NaN             NaN  Virginia  United States        NaN  0.006673                 NaN               NaN
1   2019      2      9295              58        NaN   2019-02       -0.060257                NaN       -0.121212  Virginia  United States        NaN  0.006240                 NaN         -0.064864
2   2019      3     10200              60        NaN   2019-03        0.097364                NaN        0.034483  Virginia  United States        NaN  0.005882                 NaN         -0.057302
3   2019      4     10138              61        NaN   2019-04       -0.006078                NaN        0.016667  Virginia  United States        NaN  0.006017                 NaN          0.022884
4   2019      5     11178              74        NaN   2019-05        0.102584                NaN        0.213115  Virginia  United States        NaN  0.006620                 NaN          0.100247
5   2019      6     10590              68        NaN   2019-06       -0.052603                NaN       -0.081081  Virginia  United States        NaN  0.006421                 NaN         -0.030059
6   2019      7     10305              62        NaN   2019-07       -0.026912                NaN       -0.088235  Virginia  United States        NaN  0.006016                 NaN         -0.063019
7   2019      8     10495              72        NaN   2019-08        0.018438                NaN        0.161290  Virginia  United States        NaN  0.006860                 NaN          0.140266
8   2019      9      9770              83        NaN   2019-09       -0.069081                NaN        0.152778  Virginia  United States        NaN  0.008495                 NaN          0.238322
9   2019     10     12568              86        NaN   2019-10        0.286387                NaN        0.036145  Virginia  United States        NaN  0.006843                 NaN         -0.194531
10  2019     11     12142              71        NaN   2019-11       -0.033896                NaN       -0.174419  Virginia  United States        NaN  0.005847                 NaN         -0.145453
11  2019     12     11600              66        NaN   2019-12       -0.044638                NaN       -0.070423  Virginia  United States        NaN  0.005690                 NaN         -0.026989
12  2020      1      9867              71        NaN   2020-01       -0.149397                NaN        0.075758  Virginia  United States        NaN  0.007196                 NaN          0.264699
13  2020      2      9179              61        NaN   2020-02       -0.069727                NaN       -0.140845  Virginia  United States        NaN  0.006646                 NaN         -0.076448
14  2020      3      7306              57        NaN   2020-03       -0.204053                NaN       -0.065574  Virginia  United States        NaN  0.007802                 NaN          0.173980
15  2020      4      5202              52        NaN   2020-04       -0.287982                NaN       -0.087719  Virginia  United States        NaN  0.009996                 NaN          0.281262

## MonthYear

In [11]:
dataSubMonthYear = data[['Month', 'Year','Crash_ID','Crash_Fatal_Fl','Death_Cnt','yearMonth']].sort_values(by=['Month', 'Year'])

In [12]:
dataSubMonthYear['crashPctChange'] = dataSubMonthYear.groupby('Month')['Crash_ID'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['deathCntPctChange'] = dataSubMonthYear.groupby('Month')['Death_Cnt'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatalPctChange'] = dataSubMonthYear.groupby('Month')['Crash_Fatal_Fl'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['State']='Virginia'
dataSubMonthYear['Country']='United States'

In [13]:
dataSubMonthYear['deathRate']=dataSubMonthYear['Death_Cnt']/dataSubMonthYear['Crash_ID']
dataSubMonthYear['fatRate']=dataSubMonthYear['Crash_Fatal_Fl']/dataSubMonthYear['Crash_ID']

In [14]:
dataSubMonthYear['deathRatePctChange'] = dataSubMonthYear.groupby('Month')['deathRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))
dataSubMonthYear['fatRatePctChange'] = dataSubMonthYear.groupby('Month')['fatRate'].apply(lambda x: x.div(x.iloc[0]).subtract(1))

In [15]:
with open("VA_dataSubMonthYear.csv",'w',newline='') as outputfile:
    dataSubMonthYear.to_csv(outputfile, header=True, index = False)

In [16]:
datacheck = pd.read_csv('VA_dataSubMonthYear.csv')
datacheck.shape

(16, 15)

In [17]:
datacheck

    Month  Year  Crash_ID  Crash_Fatal_Fl  Death_Cnt yearMonth  crashPctChange  deathCntPctChange  fatalPctChange     State        Country  deathRate   fatRate  deathRatePctChange  fatRatePctChange
0       1  2019      9891              66        NaN   2019-01        0.000000                NaN        0.000000  Virginia  United States        NaN  0.006673                 NaN          0.000000
1       1  2020      9867              71        NaN   2020-01       -0.002426                NaN        0.075758  Virginia  United States        NaN  0.007196                 NaN          0.078374
2       2  2019      9295              58        NaN   2019-02        0.000000                NaN        0.000000  Virginia  United States        NaN  0.006240                 NaN          0.000000
3       2  2020      9179              61        NaN   2020-02       -0.012480                NaN        0.051724  Virginia  United States        NaN  0.006646                 NaN          0.065015
4       3  2019     10200              60        NaN   2019-03        0.000000                NaN        0.000000  Virginia  United States        NaN  0.005882                 NaN          0.000000
5       3  2020      7306              57        NaN   2020-03       -0.283725                NaN       -0.050000  Virginia  United States        NaN  0.007802                 NaN          0.326307
6       4  2019     10138              61        NaN   2019-04        0.000000                NaN        0.000000  Virginia  United States        NaN  0.006017                 NaN          0.000000
7       4  2020      5202              52        NaN   2020-04       -0.486881                NaN       -0.147541  Virginia  United States        NaN  0.009996                 NaN          0.661328
8       5  2019     11178              74        NaN   2019-05        0.000000                NaN        0.000000  Virginia  United States        NaN  0.006620                 NaN          0.000000
9       6  2019     10590              68        NaN   2019-06        0.000000                NaN        0.000000  Virginia  United States        NaN  0.006421                 NaN          0.000000
10      7  2019     10305              62        NaN   2019-07        0.000000                NaN        0.000000  Virginia  United States        NaN  0.006016                 NaN          0.000000
11      8  2019     10495              72        NaN   2019-08        0.000000                NaN        0.000000  Virginia  United States        NaN  0.006860                 NaN          0.000000
12      9  2019      9770              83        NaN   2019-09        0.000000                NaN        0.000000  Virginia  United States        NaN  0.008495                 NaN          0.000000
13     10  2019     12568              86        NaN   2019-10        0.000000                NaN        0.000000  Virginia  United States        NaN  0.006843                 NaN          0.000000
14     11  2019     12142              71        NaN   2019-11        0.000000                NaN        0.000000  Virginia  United States        NaN  0.005847                 NaN          0.000000
15     12  2019     11600              66        NaN   2019-12        0.000000                NaN        0.000000  Virginia  United States        NaN  0.005690                 NaN          0.000000

#### The december tied data
In this section we compare the all the months we have in 2020 to the most recent "normal month" which is December.

In [18]:
compare = dataSubYearMonth[['yearMonth', 'Crash_ID', 'Crash_Fatal_Fl']][dataSubYearMonth.yearMonth >= '2019-12']

compare['crashPctChangeCompareDec'] = compare.Crash_ID / compare.Crash_ID.iloc[0] - 1
compare['fatalPctChangeCompareDec'] = compare.Crash_Fatal_Fl / compare.Crash_Fatal_Fl.iloc[0] - 1

compare['State']='Virginia'
compare['Country']='United States'

In [19]:
compare

   yearMonth  Crash_ID  Crash_Fatal_Fl  crashPctChangeCompareDec  fatalPctChangeCompareDec     State        Country
11   2019-12     11600              66                  0.000000                  0.000000  Virginia  United States
12   2020-01      9867              71                 -0.149397                  0.075758  Virginia  United States
13   2020-02      9179              61                 -0.208707                 -0.075758  Virginia  United States
14   2020-03      7306              57                 -0.370172                 -0.136364  Virginia  United States
15   2020-04      5202              52                 -0.551552                 -0.212121  Virginia  United States

In [20]:
with open("VA_PctChangeCompareDec.csv",'w',newline='') as outputfile:
    compare.to_csv(outputfile, header=True, index = False)